table athlete
	lineageTag: df7700aa-6d88-4103-a6be-b7383e777e73

	column 'Age Bucket' = ```
			
			SWITCH(
			    TRUE(),
			    ISBLANK(athlete[Age]), BLANK(),
			    athlete[Age] < 20, "Under 20",
			    athlete[Age] >= 20 && athlete[Age] < 31, "Between 20 & 30",
			    athlete[Age] >= 31 && athlete[Age] < 51, "Between 30 & 50",
			    athlete[Age] > 50, "Over 50"
			)
			
			```
		lineageTag: 912ea09c-0e06-4c3f-b675-23a57e3a3330
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	column ID
		dataType: int64
		formatString: 0
		lineageTag: da2f4a06-7b8e-4ece-958d-dfec589b5381
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: 67cb5fb8-9af7-4578-8dfb-41505e3d71ee
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	column Sex
		dataType: string
		lineageTag: 276981e3-381d-41a1-988b-e5de19776c0a
		summarizeBy: none
		sourceColumn: Sex

		annotation SummarizationSetBy = Automatic

	column Age
		dataType: int64
		formatString: 0
		lineageTag: 8184fe6d-6ce1-469a-be50-e338d2e7d8d1
		summarizeBy: sum
		sourceColumn: Age

		annotation SummarizationSetBy = Automatic

	column Height
		dataType: double
		lineageTag: a8726fde-7091-4e38-9d41-1474edbf94f6
		summarizeBy: sum
		sourceColumn: Height

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Weight
		dataType: double
		lineageTag: aa7a6f4a-1eb2-4654-9445-03bf9465cece
		summarizeBy: sum
		sourceColumn: Weight

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Team
		dataType: string
		lineageTag: 39e7d0a4-3510-4c74-b028-629e2d8cacba
		summarizeBy: none
		sourceColumn: Team

		annotation SummarizationSetBy = Automatic

	column NOC
		dataType: string
		lineageTag: 315c6b7a-7e92-496f-96a0-8dfab77dd73d
		summarizeBy: none
		sourceColumn: NOC

		annotation SummarizationSetBy = Automatic

	column Games
		dataType: string
		lineageTag: 392bafa8-b6f6-49d8-b58e-88dd88563c35
		summarizeBy: none
		sourceColumn: Games

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 6093d1c7-5212-40bd-860a-d616d771e374
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Season
		dataType: string
		lineageTag: 01864e4c-aa4b-4a5f-a081-a52eed0ed9f7
		summarizeBy: none
		sourceColumn: Season

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: f8228769-dc0f-4d89-932d-9ff177de5273
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column Sport
		dataType: string
		lineageTag: 50a11d32-2162-404a-a41a-a9039b0d19d7
		summarizeBy: none
		sourceColumn: Sport

		annotation SummarizationSetBy = Automatic

	column Event
		dataType: string
		lineageTag: 6e02aafd-2c93-47da-a27b-d0b9a8209076
		summarizeBy: none
		sourceColumn: Event

		annotation SummarizationSetBy = Automatic

	column Medal
		dataType: string
		lineageTag: 818f7075-7804-4ba9-91ad-395747f40d0e
		summarizeBy: none
		sourceColumn: Medal

		annotation SummarizationSetBy = Automatic

	partition athlete = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\aaa69\OneDrive\Documents\Olympics_Dashboard\athlete.csv"),[Delimiter=",", Columns=15, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"En-têtes promus" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Type modifié" = Table.TransformColumnTypes(#"En-têtes promus",{{"ID", Int64.Type}, {"Name", type text}, {"Sex", type text}, {"Age", Int64.Type}, {"Height", type number}, {"Weight", type number}, {"Team", type text}, {"NOC", type text}, {"Games", type text}, {"Year", Int64.Type}, {"Season", type text}, {"City", type text}, {"Sport", type text}, {"Event", type text}, {"Medal", type text}}),
				    #"Erreurs remplacées" = Table.ReplaceErrorValues(#"Type modifié", {{"Age", null}}),
				    #"Erreurs remplacées1" = Table.ReplaceErrorValues(#"Erreurs remplacées", {{"Height", null}}),
				    #"Erreurs remplacées2" = Table.ReplaceErrorValues(#"Erreurs remplacées1", {{"Weight", null}})
				in
				    #"Erreurs remplacées2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

